export const english = [
  "apple", "table", "grape", "water", "stone", "chair", "piano", "music", "lemon", "bird",
  "house", "watch", "happy", "world", "cloud", "light", "night", "dance", "money", "peace",
  "tiger", "movie", "party", "sleep", "fight", "green", "brown", "black", "white", "lucky",
  "trick", "friend", "ghost", "dream", "sword", "heart", "fire", "rain", "storm", "winter",
  "summer", "autumn", "spring", "pencil", "orange", "banana", "planet", "water", "game", "star",
  "earth", "moon", "sun", "ocean", "beach", "desert", "mountain", "forest", "desire", "candy",
  "paper", "school", "river", "speed", "alien", "truth", "lions", "cars", "bride", "child",
  "faith", "camera", "laptop", "keyboard", "screen", "phone", "black", "white", "green", "red",
  "blue", "yellow", "orange", "pink", "purple", "brown", "gray", "fresh", "old", "new", "start",
  "end", "open", "close", "jump", "run", "fly", "walk", "work", "home", "goal", "head", "heart",
  "mind", "love", "hate", "fun", "fast", "slow", "bright", "dark", "soft", "hard", "rich", "poor",
  "small", "large", "big", "tiny", "strong", "weak", "wise", "smart", "dumb", "lazy", "hardy",
  "sweet", "bitter", "sour", "salty", "hot", "cold", "warm", "cool", "wind", "rain", "snow", "ice",
  "fire", "house", "garden", "sky", "free", "city", "town", "road", "path", "way", "light", "dark",
  "hollow", "tall", "short", "wide", "narrow", "color", "style", "letter", "mind", "wish", "hug",
  "gift", "death", "life", "search", "find", "seek", "run", "fly", "catch", "fall", "climb", "sit",
  "rise", "sight", "touch", "sense", "hear", "see", "feel", "think", "do", "say", "sing", "read",
  "study", "paint", "draw", "write", "speak", "tell", "ask", "talk", "sing", "dance", "paint", 
  "swim", "help", "ask", "give", "take", "buy", "sell", "pay", "earn", "spend", "save", "go", "stop",
  "travel", "move", "rest", "change", "stay", "win", "lose", "try", "catch", "throw", "start", 
  "finish", "begin", "end", "pause", "stop", "stay", "play", "score", "best", "happy", "sad", 
  "angry", "calm", "surprise", "shock", "confused", "sad", "laugh", "cry", "win", "top", "good",
  "bad", "beautiful", "ugly", "strong", "weak", "brave", "fear", "hope", "truth", "laugh", "funny",
  "soft", "hard", "kind", "helpful", "cruel", "mean", "shy", "loud", "quiet", "reliable", "loyal",
  "faithful", "trustworthy", "sensitive", "caring", "aggressive", "rude", "cheerful", "silent",
  "bright", "peaceful", "kind", "selfish", "stubborn", "optimistic", "pessimistic", "humble",
  "modest", "bold", "courageous", "generous", "hopeful", "fame", "legacy", "first", "second", 
  "third", "after", "before", "second", "growth", "perfect", "rising", "advancing", "accelerate",
  "race", "move", "try", "push", "think", "work", "realize", "learn", "freedom", "chase", "shine",
  "overcome", "master", "survival", "fearless", "hero", "focus", "trick", "grateful", "strength",
  "strategy", "innovate", "create", "passion", "skills", "achieve", "perform", "finish", "resolve",
  "solve", "simplify", "organize", "keep", "help", "begin", "continue", "finish", "become",
  "innovate", "strive", "grow", "learn", "work", "succeed", "reflect", "wish", "aim", "goal",
  "target", "vision", "light", "darkness", "night", "day", "cycle", "energy", "movement", "drive",
  "idea", "hope", "dream", "soul", "vision", "ambition", "passion", "comfort", "strength", "resolve"
];

export const swedish = [
  "äpple", "bord", "druva", "vatten", "sten", "stol", "piano", "musik", "citron", "fågel",
  "hus", "klocka", "glad", "värld", "moln", "ljus", "natt", "dans", "pengar", "fred",
  "tiger", "film", "fest", "sömn", "kamp", "grön", "brun", "svart", "vit", "tur",
  "trick", "vän", "spöke", "dröm", "svärd", "hjärta", "eld", "regn", "storm", "vinter",
  "sommar", "höst", "vår", "penna", "apelsin", "banan", "planet", "spel", "stjärna",
  "jord", "måne", "sol", "hav", "strand", "öken", "berg", "skog", "önskan", "godis",
  "papper", "skola", "flod", "hastighet", "alien", "sanning", "lejon", "bilar", "brud", "barn",
  "tro", "kamera", "laptop", "tangentbord", "skärm", "telefon", "röd", "blå", "gul", "grå",
  "rosa", "lila", "orange", "vit", "svart", "ny", "gammal", "start", "slut", "öppna",
  "stänga", "hoppa", "springa", "flyga", "gå", "jobba", "mål", "huvud", "hjärna",
  "kärlek", "hat", "kul", "snabb", "långsam", "klar", "mörk", "mjuk", "hård", "rik", "fattig",
  "liten", "stor", "enorm", "pytteliten", "stark", "svag", "smart", "dum", "lat", "söt",
  "bitter", "sur", "salt", "varm", "kall", "ljummen", "sval", "vind", "snö", "is",
  "brand", "trädgård", "himmel", "fri", "stad", "by", "väg", "stig", "ljus", "tom",
  "hög", "kort", "bred", "smal", "färg", "stil", "bokstav", "tanke", "önska", "kram",
  "gåva", "död", "liv", "sök", "hitta", "fånga", "falla", "klättra", "sitta", "resa sig",
  "se", "höra", "känna", "tänka", "göra", "säga", "sjunga", "läsa", "måla", "rita",
  "skriva", "tala", "fråga", "prata", "simma", "hjälpa", "ge", "ta", "köpa", "sälja",
  "betala", "tjäna", "spara", "resa", "vila", "förändra", "stanna", "vinna", "förlora",
  "försöka", "kasta", "börja", "avsluta", "paus", "spela", "poäng", "bäst", "sorglig",
  "arg", "lugn", "överraskad", "chock", "förvirrad", "skratta", "gråta", "toppen",
  "bra", "dålig", "vacker", "ful", "modig", "rädd", "hopp", "sanning", "snäll",
  "hjälpsam", "elak", "blyg", "högljudd", "tyst", "pålitlig", "lojal", "trogen",
  "ärlig", "känslig", "omtänksam", "aggressiv", "oartig", "glad", "tystlåten",
  "fredlig", "självisk", "envis", "optimistisk", "pessimistisk", "ödmjuk",
  "modig", "generös", "berömd", "arv", "första", "andra", "tredje", "före", "efter",
  "växa", "perfekt", "stigande", "utvecklas", "snabba", "rörelse", "försök", "driv",
  "idé", "dröm", "själ", "ambition", "passion", "styrka", "lösning", "kreativitet",
  "skapa", "nå", "prestera", "färdig", "organisera", "börja", "fortsätta", "förändras",
  "bli", "lära", "lyckas", "reflektera", "mål", "vision", "cykel", "energi", "livskraft",
  "framtid", "utmana", "övervinna", "fokusera", "tacksam", "strategi", "innovera",
  "tänka", "klara", "kämpa", "överleva", "hjälte", "glädje", "värde", "liv", "förändring",
  "framgång", "kärlek", "mod", "drivkraft", "vilja", "beslut", "balans",
];

export const russian = [
  "яблоко", "стол", "виноград", "вода", "камень", "стул", "пианино", "музыка", "лимон", "птица",
  "дом", "часы", "счастье", "мир", "облако", "свет", "ночь", "танец", "деньги", "мир",
  "тигр", "фильм", "вечеринка", "сон", "битва", "зелёный", "коричневый", "чёрный", "белый", "счастливый",
  "обман", "друг", "призрак", "мечта", "меч", "сердце", "огонь", "дождь", "шторм", "зима",
  "лето", "осень", "весна", "карандаш", "апельсин", "банан", "планета", "игра", "звезда", "земля",
  "луна", "солнце", "океан", "пляж", "пустыня", "гора", "лес", "желание", "конфета",
  "бумага", "школа", "река", "скорость", "инопланетянин", "истина", "львы", "машины", "невеста", "ребёнок",
  "вера", "камера", "ноутбук", "клавиатура", "экран", "телефон", "чёрный", "белый", "зелёный", "красный",
  "синий", "жёлтый", "оранжевый", "розовый", "фиолетовый", "коричневый", "серый", "свежий", "старый",
  "новый", "начало", "конец", "открыть", "закрыть", "прыжок", "бегать", "летать", "идти", "работать",
  "дом", "цель", "голова", "сердце", "разум", "любовь", "ненависть", "весело", "быстро", "медленно",
  "яркий", "тёмный", "мягкий", "жёсткий", "богатый", "бедный", "маленький", "большой", "огромный", "крошечный",
  "сильный", "слабый", "умный", "глупый", "ленивый", "выносливый", "сладкий", "горький", "кислый", "солёный",
  "горячий", "холодный", "тёплый", "прохладный", "ветер", "дождь", "снег", "лёд", "пожар", "сад",
  "небо", "свобода", "город", "посёлок", "дорога", "путь", "свет", "тёмный", "пустой", "высокий",
  "короткий", "широкий", "узкий", "цвет", "стиль", "буква", "желание", "объятие", "подарок",
  "смерть", "жизнь", "поиск", "найти", "искать", "бежать", "летать", "ловить", "падать", "взбираться",
  "сидеть", "вставать", "видеть", "слышать", "ощущать", "думать", "делать", "сказать", "петь", "читать",
  "учиться", "рисовать", "писать", "говорить", "спрашивать", "болтать", "петь", "танцевать", "плавать", 
  "помощь", "давать", "брать", "покупать", "продавать", "платить", "заработать", "тратить", "сохранять", "идти",
  "остановиться", "путешествовать", "двигаться", "отдыхать", "изменять", "оставаться", "выигрывать", "проигрывать",
  "пробовать", "ловить", "бросать", "начать", "закончить", "начинать", "пауза", "стоп", "играть", "набирать",
  "лучший", "счастливый", "грустный", "злой", "спокойный", "удивление", "шок", "путаница", "смеяться", "плакать",
  "выиграть", "топ", "хорошо", "плохо", "красивый", "уродливый", "смелый", "страх", "надежда", "истина",
  "смеяться", "смешной", "мягкий", "жёсткий", "добрый", "помощь", "жестокий", "злой", "трус", "громкий",
  "тихий", "надёжный", "преданный", "верный", "честный", "чувствительный", "заботливый", "агрессивный", "грубый",
  "радостный", "молчаливый", "яркий", "мирный", "себе", "упрямый", "оптимистичный", "пессимистичный", "скромный",
  "большой", "смелый", "мужественный", "щедрый", "надежда", "слава", "наследие", "первый", "второй", 
  "третий", "после", "до", "второй", "рост", "совершенство", "восходящий", "развивающийся", "ускорять",
  "гонка", "двигаться", "пробовать", "толкать", "думать", "работать", "реализовывать", "учить", "свобода", "погоня",
  "сиять", "преодолеть", "освободить", "выживание", "бесстрашный", "герой", "фокус", "обман", "благодарность",
  "сила", "стратегия", "инновация", "создание", "страсть", "умения", "достижение", "выступать", "завершить", "решить",
  "упростить", "организовать", "сохранить", "помощь", "начать", "продолжить", "закончить", "стать", "инновация",
  "стремиться", "расти", "учиться", "работать", "успех", "отражение", "желание", "цель", "мишень", "видение",
  "свет", "тьма", "ночь", "день", "цикл", "энергия", "движение", "двигатель", "идея", "надежда", "мечта", "душа",
  "видение", "амбиция", "страсть", "комфорт", "сила", "решение"
];